CREATE TABLE madlib_entries (
id INT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,
noun VARCHAR(30) NOT NULL,
adjective VARCHAR(30) NOT NULL,
verb VARCHAR(30) NOT NULL,
adverb VARCHAR(30) NOT NULL,
story VARCHAR(200)
);

